[project]
name = "code"
version = "0.1.0"
description = "MS THESIS"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.1",
    "networkx>=3.4.2",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "ruff>=0.9.10",
]
